name: build nereba

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install DevKit Pro
      run: sudo installer -pkg devkitpro-pacman-installer.pkg -target /
           xcode-select --install

    - name: make
      run: make

      
