name: build nereba

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install DevKit Pro
      run: wget https://apt.devkitpro.org/install-devkitpro-pacman
            chmod +x ./install-devkitpro-pacman
            sudo ./install-devkitpro-pacman
           sudo ln -s /proc/self/mounts /etc/mtab

    - name: make
      run: make

      
